// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package autogen

import (
	"time"
)

type NewUserInput struct {
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Location string    `json:"location"`
	Language string    `json:"language"`
	JoinDate time.Time `json:"joinDate"`
}
